cooking_ingredients = [
    {
        "name": "apple",
        "emoji": "🍎",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["apple"],
    },
    {
        "name": "banana",
        "emoji": "🍌",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["banana"],
    },
    {
        "name": "carrot",
        "emoji": "🥕",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["carrot"],
    },
    {
        "name": "egg",
        "emoji": "🥚",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["eggs and dairy"],
        "all_ingredients": ["egg"],
    },
    {
        "name": "raw fish",
        "emoji": "🐟",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["meat"],
        "all_ingredients": ["raw fish"],
    },
    {
        "name": "raw meat",
        "emoji": "🥩",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["meat"],
        "all_ingredients": ["raw meat"],
    },
    {
        "name": "raw rice",
        "emoji": "🌾",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["grain"],
        "all_ingredients": ["raw rice"],
    },
    {
        "name": "wheat",
        "emoji": "🌾",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["grain"],
        "all_ingredients": ["wheat"],
    },
    {
        "name": "cheese",
        "emoji": "🧀",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["eggs and dairy"],
        "all_ingredients": ["cheese"],
    },
    {
        "name": "butter",
        "emoji": "🧈",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["eggs and dairy"],
        "all_ingredients": ["butter"],
    },
    {
        "name": "lettuce",
        "emoji": "🥬",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["lettuce"],
    },
    {
        "name": "tomato",
        "emoji": "🍅",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["tomato"],
    },
    {
        "name": "onion",
        "emoji": "🧅",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["onion"],
    },
    {
        "name": "ginger",
        "emoji": "🫚",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["ginger"],
    },
    {
        "name": "potato",
        "emoji": "🥔",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["potato"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["mushroom"],
    },
    {
        "name": "pepper",
        "emoji": "🌶️",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["pepper"],
    },
    {
        "name": "coconut",
        "emoji": "🥥",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["coconut"],
    },
    {
        "name": "pineapple",
        "emoji": "🍍",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["pineapple"],
    },
]

cooking_tools = [
    {"name": "water", "emoji": "💧", "tool": True},
    {"name": "knife", "emoji": "🔪", "tool": True},
    {"name": "stove", "emoji": "🔥", "tool": True},
    {"name": "salt", "emoji": "🧂", "tool": True},
]

decorations_tools = [
    {"name": "scissors", "emoji": "✂️", "tool": True},
    {"name": "paint", "emoji": "🎨", "tool": True},
    {"name": "frame", "emoji": "🖼️", "tool": True},
    {"name": "pen", "emoji": "🖊️", "tool": True},
]

decorations_ingredients = [
    {
        "name": "leaf",
        "emoji": "🍃",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["leaf"],
    },
    {
        "name": "rock",
        "emoji": "🪨",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["rock"],
    },
    {
        "name": "wood",
        "emoji": "🪵",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["wood"],
    },
    {
        "name": "paper",
        "emoji": "📄",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["paper"],
    },
    {
        "name": "yarn",
        "emoji": "🧶",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["yarn"],
    },
    {
        "name": "flower",
        "emoji": "🌸",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["flower"],
    },
    {
        "name": "sunflower",
        "emoji": "🌻",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["sunflower"],
    },
    {
        "name": "thread",
        "emoji": "🧵",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["thread"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["mushroom"],
    },
    {
        "name": "feather",
        "emoji": "🪶",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["feather"],
    },
    {
        "name": "shell",
        "emoji": "🐚",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["shell"],
    },
    {
        "name": "pinecone",
        "emoji": "🌲",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["pinecone"],
    },
    {
        "name": "acorn",
        "emoji": "🌰",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["acorn"],
    },
    {
        "name": "bark",
        "emoji": "🪵",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["bark"],
    },
    {
        "name": "beads",
        "emoji": "📿",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["beads"],
    },
    {
        "name": "ribbon",
        "emoji": "🎀",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["ribbon"],
    },
    {
        "name": "cardboard",
        "emoji": "📦",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["cardboard"],
    },
    {
        "name": "newspaper",
        "emoji": "📰",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["newspaper"],
    },
    {
        "name": "buttons",
        "emoji": "🔘",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["buttons"],
    },
    {
        "name": "glitter",
        "emoji": "✨",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["glitter"],
    },
]

animals_tools = [
    {"name": "growth serum", "emoji": "🌡️", "tool": True},
    {"name": "mutation catalyst", "emoji": "🧬", "tool": True},
    {"name": "respiratory reconfigurer", "emoji": "🌀", "tool": True},
    {"name": "metabolic accelerator", "emoji": "⚡", "tool": True},
]


animals_ingredients = [
    {
        "name": "trout",
        "emoji": "🐟",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "original_respiratory_types": ["gills"],
        "habitats": ["water"],
        "basic_animals": ["trout"],
    },
    {
        "name": "shark",
        "emoji": "🦈",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["shark"],
    },
    {
        "name": "octopus",
        "emoji": "🐙",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["octopus"],
    },
    {
        "name": "squid",
        "emoji": "🦑",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["squid"],
    },
    {
        "name": "crab",
        "emoji": "🦀",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["crab"],
    },
    {
        "name": "pufferfish",
        "emoji": "🐡",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["pufferfish"],
    },
    {
        "name": "snake",
        "emoji": "🐍",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["snake"],
    },
    {
        "name": "frog",
        "emoji": "🐸",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["frog"],
    },
    {
        "name": "bird",
        "emoji": "🐦‍⬛",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "omnivore",
        "habitats": ["air"],
        "basic_animals": ["bird"],
    },
    {
        "name": "bee",
        "emoji": "🐝",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["air"],
        "basic_animals": ["bee"],
    },
    {
        "name": "butterfly",
        "emoji": "🦋",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["air"],
        "basic_animals": ["butterfly"],
    },
    {
        "name": "lizard",
        "emoji": "🦎",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["lizard"],
    },
    {
        "name": "elephant",
        "emoji": "🐘",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["elephant"],
    },
    {
        "name": "whale",
        "emoji": "🐳",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["whale"],
    },
    {
        "name": "panda",
        "emoji": "🐼",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["panda"],
    },
    {
        "name": "kangaroo",
        "emoji": "🦘",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["kangaroo"],
    },
    {
        "name": "lion",
        "emoji": "🦁",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["lion"],
    },
    {
        "name": "giraffe",
        "emoji": "🦒",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["giraffe"],
    },
    {
        "name": "zebra",
        "emoji": "🦓",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["zebra"],
    },
    {
        "name": "monkey",
        "emoji": "🐒",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "omnivore",
        "habitats": ["land"],
        "basic_animals": ["monkey"],
    },
]


potions_tools = [
    {"name": "vial", "emoji": "🧪", "tool": True},
    {"name": "mortar", "emoji": "🏺", "tool": True},
    {"name": "wand", "emoji": "🪄", "tool": True},
    {"name": "filter", "emoji": "🧫", "tool": True},
]

potions_ingredients = [
    {
        "name": "frog leg",
        "emoji": "🐸",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["frog leg"],
    },
    {
        "name": "bat wing",
        "emoji": "🦇",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["bat wing"],
    },
    {
        "name": "dragon scale",
        "emoji": "🐉",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["dragon scale"],
    },
    {
        "name": "unicorn horn",
        "emoji": "🦄",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["unicorn horn"],
    },
    {
        "name": "mandrake root",
        "emoji": "🌱",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["mandrake root"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["mushroom"],
    },
    {
        "name": "dandelion",
        "emoji": "🌼",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["dandelion"],
    },
    {
        "name": "rose petal",
        "emoji": "🌹",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["rose petal"],
    },
    {
        "name": "sunstone",
        "emoji": "☀️",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["mineral"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["sunstone"],
    },
    {
        "name": "obsidian",
        "emoji": "⚫",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["mineral"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["obsidian"],
    },
    {
        "name": "amber",
        "emoji": "🟠",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["mineral"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["amber"],
    },
    {
        "name": "whispering wind",
        "emoji": "🌬️",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["whispering wind"],
    },
    {
        "name": "ghostly vapor",
        "emoji": "👻",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["ghostly vapor"],
    },
    {
        "name": "volcanic fumes",
        "emoji": "🌋",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["volcanic fumes"],
    },
    {
        "name": "dragon's breath",
        "emoji": "🔥",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["dragon's breath"],
    },
    {
        "name": "basilisk venom",
        "emoji": "⚗️",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["basilisk venom"],
    },
    {
        "name": "morning dew",
        "emoji": "💧",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["morning dew"],
    },
    {
        "name": "kraken ink",
        "emoji": "🦑",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["kraken ink"],
    },
    {
        "name": "honey nectar",
        "emoji": "🍯",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["honey nectar"],
    },
    {
        "name": "tree sap",
        "emoji": "🌳",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["tree sap"],
    },
]


TOOLS = {
    "cooking": cooking_tools,
    "decorations": decorations_tools,
    "animals": animals_tools,
    "potions": potions_tools,
}

INGREDIENTS = {
    "cooking": cooking_ingredients,
    "decorations": decorations_ingredients,
    "animals": animals_ingredients,
    "potions": potions_ingredients,
}


cooking_system_prompt = """
You are controlling the semantics of a cooking game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- If an item's salt level is salted, its name should include "salted". If it is oversalted, it should include "oversalted".
- If an item's cook level is cooked, its name should include "cooked". If it is overcooked, it should include "overcooked".
- If an item's water level is soaked, its name should include "soaked".
- If an item's chop level is chopped, its name should include "chopped".
- If an item is cooked and soaked, it should be called some kind of "soup".
- If an item has been cooked, it should not include the word "raw" in the name.
- Combinations of different ingredients should retain at least parts of the names of the original ingredients.

In general, the name should give the participant some sense of why the item's value is the way it is.

Please respond in JSON format, with double quotes around all strings.
"""

decorations_system_prompt = """
You are controlling the semantics of a decoration-making game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- If an item's paint level is painted, its name should include "painted". If it is overpainted, it should include "messy".
- If an item's cut level is cut, its name should include "cut"
- If an item's drawn level is drawn and it is on an artificial material, its name should include "drawn-on." If it is on a natural material, it should include "scribbled-on."
- If an item is framed, its name should include "framed."
- If an item has post-frame-messed-with, it should not have "framed" in its name anymore and have "with ruined frame" at the end of its name.
- Combinations of different decoration parts should retain at least parts of the names of the original parts.

In general, the name should give the participant some sense of why the item's value is the way it is.

Please respond in JSON format, with double quotes around all strings.
"""

animals_system_prompt = """
You are controlling the semantics of a hybrid animal creation game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- If an animal's respiratory type is not the same as its original respiratory type, its name should include "with gills" or "with lungs", depending on the new respiratory type. If the respiratory type is "confused", it should include "with breathing problems".
- The animal's mutation level is mutant, super-mutant, or corrupted, it should be included in the name.
- If an animal's growth level is jumbo or colossal, its name should include the growth level.
- If an animal is a herbivore and its metabolic level is "accelerated", its name should include "starving". If it is a carnivore or omnivore, it should include "energetic".
- If an animal's list of habitats includes both land and water, its name should include "amphibious".
- Combinations of different animals should retain at least parts of the names of the original animals.

In general, the name should give the participant some sense of why the item's value is the way it is.

Please respond in JSON format, with double quotes around all strings.
"""

potions_system_prompt = """
You are controlling the semantics of a potion brewing game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- An item that has an enchantment level of "flickering," "glowing," or "corrupted" should have its enchantment level in the name.
- If an item's filtering is "filtered," its name should include "filtered." If it is "botched," its name should include "with failed filtering"
- If an item's extraction is "extracted," its name should include "extracted." If it is "botched," its name should include "with botched extraction"
- If an item's grind is "ground," its name should include "ground". If it is "botched," its name should include "poorly ground"
- Combinations of different ingredients should retain at least parts of the names of the original ingredients.

In general, the name should give the participant some sense of why the item's value is the way it is.

Please respond in JSON format, with double quotes around all strings.
"""

SYSTEM_PROMPTS = {
    "cooking": cooking_system_prompt,
    "decorations": decorations_system_prompt,
    "animals": animals_system_prompt,
    "potions": potions_system_prompt,
}

cooking_ic_examples = [
    {
        "input": [
            {
                "tool": False,
                "salt_level": 0,
                "cook_level": 0,
                "water_level": 0,
                "chop_level": 1,
                "edible": True,
                "ingredient_types": ["vegetable"],
                "all_ingredients": ["potato"],
                "value": 15,
                "name": "Sliced Potato",
                "emoji": "🔪🥔",
            },
            {
                "tool": False,
                "salt_level": 0,
                "cook_level": 1,
                "water_level": 0,
                "chop_level": 0,
                "edible": True,
                "ingredient_types": ["aromatic"],
                "all_ingredients": ["ginger"],
                "value": 15,
                "name": "Cooked Ginger",
                "emoji": "🔥🫚",
            },
        ],
        "outcome": {
            "salt_level": 0,
            "cook_level": 0,
            "water_level": 0,
            "chop_level": 0,
            "edible": True,
            "ingredient_types": ["vegetable", "aromatic"],
            "all_ingredients": ["potato", "ginger"],
            "tool": False,
            "value": 20,
        },
        "semantics": {"emoji": "🥔🫚", "name": "Sliced potato with cooked ginger"},
    },
    {
        "input": [
            {"name": "stove", "emoji": "🔥", "tool": True},
            {
                "tool": False,
                "salt_level": 1,
                "cook_level": 0,
                "water_level": 1,
                "chop_level": 1,
                "edible": True,
                "ingredient_types": ["vegetable"],
                "all_ingredients": ["tomato"],
                "value": 0,
                "name": "Salted Soaked Chopped Tomato",
                "emoji": "🍅💧🧂",
            },
        ],
        "outcome": {
            "tool": False,
            "salt_level": 1,
            "cook_level": 1,
            "water_level": 1,
            "chop_level": 1,
            "edible": True,
            "ingredient_types": ["vegetable"],
            "all_ingredients": ["tomato"],
            "value": 65,
        },
        "semantics": {"emoji": "🍅🔥🧂", "name": "Salted Tomato Soup"},
    },
]

animals_ic_examples = [
    {
        "input": [
            {
                "name": "elephant",
                "emoji": "🐘",
                "tool": False,
                "size": "large",
                "mutation_level": 0,
                "respiratory_type": "lungs",
                "original_respiratory_types": ["lungs"],
                "metabolic_level": 0,
                "growth_level": 0,
                "diet_type": "herbivore",
                "habitats": ["land"],
                "basic_animals": ["elephant"],
                "value": 0,
            },
            {
                "name": "giraffe",
                "emoji": "🦒",
                "tool": False,
                "size": "large",
                "mutation_level": 0,
                "respiratory_type": "lungs",
                "original_respiratory_types": ["lungs"],
                "metabolic_level": 0,
                "growth_level": 0,
                "diet_type": "herbivore",
                "habitats": ["land"],
                "basic_animals": ["giraffe"],
                "value": 0,
            },
        ],
        "outcome": {
            "habitats": ["land", "land"],
            "size": "large",
            "growth_level": 0,
            "mutation_level": 0,
            "metabolic_level": 0,
            "respiratory_type": "lungs",
            "diet_type": "herbivore",
            "basic_animals": ["elephant", "giraffe"],
            "original_respiratory_types": ["lungs", "lungs"],
            "tool": False,
            "value": 0,
        },
        "semantics": {"emoji": "🐘🦒", "name": "elepharaffe"},
    },
    {
        "input": [
            {"name": "growth serum", "emoji": "🌡️", "tool": True},
            {
                "tool": False,
                "size": "large",
                "mutation_level": 1,
                "respiratory_type": "lungs",
                "original_respiratory_types": ["lungs"],
                "metabolic_level": 0,
                "growth_level": 0,
                "diet_type": "carnivore",
                "habitats": ["water"],
                "basic_animals": ["whale"],
                "value": -15,
                "name": "mutant whale",
                "emoji": "🐳🧬",
            },
        ],
        "outcome": {
            "tool": False,
            "size": "large",
            "mutation_level": 1,
            "respiratory_type": "lungs",
            "original_respiratory_types": ["lungs"],
            "metabolic_level": 0,
            "growth_level": 1,
            "diet_type": "carnivore",
            "habitats": ["water"],
            "basic_animals": ["whale"],
            "value": -30,
        },
        "semantics": {"emoji": "🐳🧬🌡", "name": "overgrown mutant whale"},
    },
]

potions_ic_examples = [
    {
        "input": [
            {
                "name": "obsidian",
                "emoji": "⚫",
                "tool": False,
                "states_of_matter": ["solid"],
                "is_hard": True,
                "ingredient_types": ["mineral"],
                "magicalities": [False],
                "enchantment_level": 0,
                "filtering": None,
                "extraction": None,
                "grind": None,
                "basic_ingredients": ["obsidian"],
                "value": 0,
            },
            {"name": "filter", "emoji": "🧫", "tool": True},
        ],
        "outcome": {
            "tool": False,
            "states_of_matter": ["solid"],
            "is_hard": True,
            "ingredient_types": ["mineral"],
            "magicalities": [False],
            "enchantment_level": 0,
            "filtering": "botched",
            "extraction": None,
            "grind": None,
            "basic_ingredients": ["obsidian"],
            "value": -25,
        },
        "semantics": {"emoji": "🧫⚫", "name": "obsidian with failed filtering"},
    },
    {
        "input": [
            {
                "tool": False,
                "states_of_matter": ["solid"],
                "is_hard": False,
                "ingredient_types": ["plant"],
                "magicalities": [False],
                "enchantment_level": 0,
                "filtering": "botched",
                "extraction": None,
                "grind": None,
                "basic_ingredients": ["rose petal"],
                "value": -25,
                "name": "botched rose petal residue",
                "emoji": "🧫🌹",
            },
            {
                "name": "unicorn horn",
                "emoji": "🦄",
                "tool": False,
                "states_of_matter": ["solid"],
                "is_hard": True,
                "ingredient_types": ["animal"],
                "magicalities": [True],
                "enchantment_level": 0,
                "filtering": None,
                "extraction": None,
                "grind": None,
                "basic_ingredients": ["unicorn horn"],
                "value": 0,
            },
        ],
        "outcome": {
            "states_of_matter": ["solid", "solid"],
            "is_hard": False,
            "ingredient_types": ["plant", "animal"],
            "magicalities": [False, True],
            "enchantment_level": 0,
            "filtering": "botched",
            "extraction": None,
            "grind": None,
            "basic_ingredients": ["rose petal", "unicorn horn"],
            "tool": False,
            "value": 0,
        },
        "semantics": {
            "emoji": "🌹🦄",
            "name": "unicorn potion with botched rose petal residue",
        },
    },
]

decorations_ic_examples = [
    {
        "input": [
            {
                "tool": False,
                "hardness": "hard",
                "paint_level": 0,
                "cut_level": 0,
                "drawn_level": 1,
                "framed": False,
                "post_frame_messed_with": False,
                "material_types": ["artificial"],
                "basic_items": ["beads"],
                "value": 25,
                "name": "drawn-on beads",
                "emoji": "📿🖊️",
            },
            {
                "name": "newspaper",
                "emoji": "📰",
                "tool": False,
                "hardness": "soft",
                "paint_level": 0,
                "cut_level": 0,
                "drawn_level": 0,
                "framed": False,
                "post_frame_messed_with": False,
                "material_types": ["artificial"],
                "basic_items": ["newspaper"],
                "value": 0,
            },
        ],
        "outcome": {
            "hardness": "hard",
            "paint_level": 0,
            "cut_level": 0,
            "drawn_level": 1,
            "material_types": ["artificial", "artificial"],
            "basic_items": ["beads", "newspaper"],
            "framed": False,
            "post_frame_messed_with": False,
            "tool": False,
            "value": 25,
        },
        "semantics": {
            "emoji": "📿📰🖊",
            "name": "newspaper decoration with drawn-on beads",
        },
    },
    {
        "input": [
            {
                "name": "sunflower",
                "emoji": "🌻",
                "tool": False,
                "hardness": "soft",
                "paint_level": 0,
                "cut_level": 0,
                "drawn_level": 0,
                "framed": False,
                "post_frame_messed_with": False,
                "material_types": ["natural"],
                "basic_items": ["sunflower"],
                "value": 0,
            },
            {"name": "pen", "emoji": "🖊️", "tool": True},
        ],
        "outcome": {
            "tool": False,
            "hardness": "soft",
            "paint_level": 0,
            "cut_level": 0,
            "drawn_level": 1,
            "framed": False,
            "post_frame_messed_with": False,
            "material_types": ["natural"],
            "basic_items": ["sunflower"],
            "value": -25,
        },
        "semantics": {"emoji": "🌻🖊️", "name": "scribbled-on sunflower"},
    },
]

IC_EXAMPLES = {
    "cooking": cooking_ic_examples,
    "decorations": decorations_ic_examples,
    "animals": animals_ic_examples,
    "potions": potions_ic_examples,
}
