cooking_ingredients = [
    {
        "name": "apple",
        "emoji": "🍎",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["apple"],
    },
    {
        "name": "banana",
        "emoji": "🍌",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["banana"],
    },
    {
        "name": "carrot",
        "emoji": "🥕",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["carrot"],
    },
    {
        "name": "egg",
        "emoji": "🥚",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["eggs_dairy"],
        "all_ingredients": ["egg"],
    },
    {
        "name": "raw fish",
        "emoji": "🐟",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["meat"],
        "all_ingredients": ["raw fish"],
    },
    {
        "name": "raw meat",
        "emoji": "🥩",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["meat"],
        "all_ingredients": ["raw meat"],
    },
    {
        "name": "raw rice",
        "emoji": "🌾",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["grain"],
        "all_ingredients": ["raw rice"],
    },
    {
        "name": "wheat",
        "emoji": "🌾",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["grain"],
        "all_ingredients": ["wheat"],
    },
    {
        "name": "cheese",
        "emoji": "🧀",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["eggs_dairy"],
        "all_ingredients": ["cheese"],
    },
    {
        "name": "butter",
        "emoji": "🧈",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["eggs_dairy"],
        "all_ingredients": ["butter"],
    },
    {
        "name": "lettuce",
        "emoji": "🥬",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["lettuce"],
    },
    {
        "name": "tomato",
        "emoji": "🍅",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["tomato"],
    },
    {
        "name": "onion",
        "emoji": "🧅",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["onion"],
    },
    {
        "name": "ginger",
        "emoji": "🫚",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["ginger"],
    },
    {
        "name": "potato",
        "emoji": "🥔",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["potato"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["mushroom"],
    },
    {
        "name": "pepper",
        "emoji": "🌶️",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["pepper"],
    },
    {
        "name": "coconut",
        "emoji": "🥥",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["coconut"],
    },
    {
        "name": "pineapple",
        "emoji": "🍍",
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["pineapple"],
    },
]

cooking_tools = [
    {"name": "water", "emoji": "💧", "tool": True},
    {"name": "knife", "emoji": "🔪", "tool": True},
    {"name": "stove", "emoji": "🔥", "tool": True},
    {"name": "salt", "emoji": "🧂", "tool": True},
]

decorations_tools = [
    {"name": "scissors", "emoji": "✂️", "tool": True},
    {"name": "paint", "emoji": "🎨", "tool": True},
    {"name": "frame", "emoji": "🖼️", "tool": True},
    {"name": "pen", "emoji": "🖊️", "tool": True},
]

decorations_ingredients = [
    {
        "name": "leaf",
        "emoji": "🍃",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["leaf"],
    },
    {
        "name": "rock",
        "emoji": "🪨",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["rock"],
    },
    {
        "name": "wood",
        "emoji": "🪵",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["wood"],
        "basic_items": ["wood"],
    },
    {
        "name": "paper",
        "emoji": "📄",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["paper"],
    },
    {
        "name": "yarn",
        "emoji": "🧶",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["yarn"],
    },
    {
        "name": "flower",
        "emoji": "🌸",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["flower"],
    },
    {
        "name": "sunflower",
        "emoji": "🌻",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["sunflower"],
    },
    {
        "name": "thread",
        "emoji": "🧵",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["thread"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["mushroom"],
    },
    {
        "name": "feather",
        "emoji": "🪶",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["feather"],
    },
    {
        "name": "shell",
        "emoji": "🐚",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["shell"],
    },
    {
        "name": "pinecone",
        "emoji": "🌲",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["pinecone"],
    },
    {
        "name": "acorn",
        "emoji": "🌰",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["acorn"],
    },
    {
        "name": "bark",
        "emoji": "🪵",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["natural"],
        "basic_items": ["bark"],
    },
    {
        "name": "beads",
        "emoji": "📿",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["beads"],
    },
    {
        "name": "ribbon",
        "emoji": "🎀",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["ribbon"],
    },
    {
        "name": "cardboard",
        "emoji": "📦",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["cardboard"],
    },
    {
        "name": "newspaper",
        "emoji": "📰",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["newspaper"],
    },
    {
        "name": "buttons",
        "emoji": "🔘",
        "tool": False,
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["buttons"],
    },
    {
        "name": "glitter",
        "emoji": "✨",
        "tool": False,
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "drawn_level": 0,
        "framed": False,
        "post_frame_messed_with": False,
        "material_types": ["artificial"],
        "basic_items": ["glitter"],
    },
]

animals_tools = [
    {"name": "growth serum", "emoji": "🌡️", "tool": True},
    {"name": "mutation catalyst", "emoji": "🧬", "tool": True},
    {"name": "respiratory reconfigurer", "emoji": "🌀", "tool": True},
    {"name": "metabolic accelerator", "emoji": "⚡", "tool": True},
]


animals_ingredients = [
    {
        "name": "trout",
        "emoji": "🐟",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "original_respiratory_types": ["gills"],
        "habitats": ["water"],
        "basic_animals": ["trout"],
    },
    {
        "name": "shark",
        "emoji": "🦈",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["shark"],
    },
    {
        "name": "octopus",
        "emoji": "🐙",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["octopus"],
    },
    {
        "name": "squid",
        "emoji": "🦑",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["squid"],
    },
    {
        "name": "crab",
        "emoji": "🦀",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["crab"],
    },
    {
        "name": "pufferfish",
        "emoji": "🐡",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "original_respiratory_types": ["gills"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["pufferfish"],
    },
    {
        "name": "snake",
        "emoji": "🐍",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["snake"],
    },
    {
        "name": "frog",
        "emoji": "🐸",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["frog"],
    },
    {
        "name": "bird",
        "emoji": "🐦‍⬛",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "omnivore",
        "habitats": ["air"],
        "basic_animals": ["bird"],
    },
    {
        "name": "bee",
        "emoji": "🐝",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["air"],
        "basic_animals": ["bee"],
    },
    {
        "name": "butterfly",
        "emoji": "🦋",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["air"],
        "basic_animals": ["butterfly"],
    },
    {
        "name": "lizard",
        "emoji": "🦎",
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["lizard"],
    },
    {
        "name": "elephant",
        "emoji": "🐘",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["elephant"],
    },
    {
        "name": "whale",
        "emoji": "🐳",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["water"],
        "basic_animals": ["whale"],
    },
    {
        "name": "panda",
        "emoji": "🐼",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["panda"],
    },
    {
        "name": "kangaroo",
        "emoji": "🦘",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["kangaroo"],
    },
    {
        "name": "lion",
        "emoji": "🦁",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "carnivore",
        "habitats": ["land"],
        "basic_animals": ["lion"],
    },
    {
        "name": "giraffe",
        "emoji": "🦒",
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["giraffe"],
    },
    {
        "name": "zebra",
        "emoji": "🦓",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "herbivore",
        "habitats": ["land"],
        "basic_animals": ["zebra"],
    },
    {
        "name": "monkey",
        "emoji": "🐒",
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "original_respiratory_types": ["lungs"],
        "metabolic_level": 0,
        "growth_level": 0,
        "diet_type": "omnivore",
        "habitats": ["land"],
        "basic_animals": ["monkey"],
    },
]


potions_tools = [
    {"name": "vial", "emoji": "🧪", "tool": True},
    {"name": "mortar", "emoji": "🏺", "tool": True},
    {"name": "wand", "emoji": "🪄", "tool": True},
    {"name": "filter", "emoji": "🧫", "tool": True},
]

potions_ingredients = [
    {
        "name": "frog leg",
        "emoji": "🐸",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["frog leg"],
    },
    {
        "name": "bat wing",
        "emoji": "🦇",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["bat wing"],
    },
    {
        "name": "dragon scale",
        "emoji": "🐉",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["dragon scale"],
    },
    {
        "name": "unicorn horn",
        "emoji": "🦄",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["unicorn horn"],
    },
    {
        "name": "mandrake root",
        "emoji": "🌱",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["mandrake root"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["mushroom"],
    },
    {
        "name": "dandelion",
        "emoji": "🌼",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["dandelion"],
    },
    {
        "name": "rose petal",
        "emoji": "🌹",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["rose petal"],
    },
    {
        "name": "sunstone",
        "emoji": "☀️",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["mineral"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["sunstone"],
    },
    {
        "name": "obsidian",
        "emoji": "⚫",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["mineral"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["obsidian"],
    },
    {
        "name": "amber",
        "emoji": "🟠",
        "tool": False,
        "states_of_matter": ["solid"],
        "is_hard": True,
        "ingredient_types": ["mineral"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["amber"],
    },
    {
        "name": "whispering wind",
        "emoji": "🌬️",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["whispering wind"],
    },
    {
        "name": "ghostly vapor",
        "emoji": "👻",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["ghostly vapor"],
    },
    {
        "name": "volcanic fumes",
        "emoji": "🌋",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["volcanic fumes"],
    },
    {
        "name": "dragon's breath",
        "emoji": "🔥",
        "tool": False,
        "states_of_matter": ["gas"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["dragon's breath"],
    },
    {
        "name": "basilisk venom",
        "emoji": "⚗️",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["basilisk venom"],
    },
    {
        "name": "morning dew",
        "emoji": "💧",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["essence"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["morning dew"],
    },
    {
        "name": "kraken ink",
        "emoji": "🦑",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["animal"],
        "magicalities": [True],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["kraken ink"],
    },
    {
        "name": "honey nectar",
        "emoji": "🍯",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["honey nectar"],
    },
    {
        "name": "tree sap",
        "emoji": "🌳",
        "tool": False,
        "states_of_matter": ["liquid"],
        "is_hard": False,
        "ingredient_types": ["plant"],
        "magicalities": [False],
        "enchantment_level": 0,
        "filtering": None,
        "extraction": None,
        "grind": None,
        "basic_ingredients": ["tree sap"],
    },
]


TOOLS = {
    "cooking": cooking_tools,
    "decorations": decorations_tools,
    "animals": animals_tools,
    "potions": potions_tools,
}

INGREDIENTS = {
    "cooking": cooking_ingredients,
    "decorations": decorations_ingredients,
    "animals": animals_ingredients,
    "potions": potions_ingredients,
}


cooking_system_prompt = """
You are controlling the semantics of a cooking game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- If an item is cooked and soaked, it should be called some kind of "soup".
- If an item has been cooked, it should not include the word "raw" in the name.

Please respond in JSON format, with double quotes around all strings.
"""

decorations_system_prompt = """
You are controlling the semantics of a decoration-making game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- If an item is framed, it should be called "framed"
- If an item has post-frame-messed-with, it should have "with ruined frame" at the end of the name

Please respond in JSON format, with double quotes around all strings.
"""

animals_system_prompt = """
You are controlling the semantics of a hybrid animal creation game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- If an animal's respiratory type is not the same as its original respiratory type, its name should include "with gills" or "with lungs", depending on the new respiratory type. If the respiratory type is "confused", it should include "with breathing problems".
- If an animal is a herbivore and its metabolic level is "accelerated", its name should include "starving".

Please respond in JSON format, with double quotes around all strings.
"""

potions_system_prompt = """
You are controlling the semantics of a potion brewing game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. The name should be informative and make it possible for the player to know the relevant features so they can learn the rules. The emoji should describe the item and its features. When in doubt it is safe to combine the emoji of the two items. If the new item has different features than any of the original items, it must get a new name.

Please keep the following rules in mind:
- An item that has an enchantment level other than unenchanted should have its enchantment level in the name.
- The name of an item that has multiple states of matter should somehow mention that it combines multiple states of matter.

Please respond in JSON format, with double quotes around all strings.
"""

SYSTEM_PROMPTS = {
    "cooking": cooking_system_prompt,
    "decorations": decorations_system_prompt,
    "animals": animals_system_prompt,
    "potions": potions_system_prompt,
}
