cooking_ingredients = [
    {
        "name": "apple",
        "emoji": "🍎",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["apple"],
    },
    {
        "name": "banana",
        "emoji": "🍌",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["banana"],
    },
    {
        "name": "carrot",
        "emoji": "🥕",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["carrot"],
    },
    {
        "name": "egg",
        "emoji": "🥚",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["eggs_dairy"],
        "all_ingredients": ["egg"],
    },
    {
        "name": "raw fish",
        "emoji": "🐟",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["meat"],
        "all_ingredients": ["raw fish"],
    },
    {
        "name": "raw meat",
        "emoji": "🥩",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["meat"],
        "all_ingredients": ["raw meat"],
    },
    {
        "name": "raw rice",
        "emoji": "🌾",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["grain"],
        "all_ingredients": ["raw rice"],
    },
    {
        "name": "wheat",
        "emoji": "🌾",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": False,
        "ingredient_types": ["grain"],
        "all_ingredients": ["wheat"],
    },
    {
        "name": "milk",
        "emoji": "🥛",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["eggs_dairy"],
        "all_ingredients": ["milk"],
    },
    {
        "name": "cheese",
        "emoji": "🧀",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["eggs_dairy"],
        "all_ingredients": ["cheese"],
    },
    {
        "name": "lettuce",
        "emoji": "🥬",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["lettuce"],
    },
    {
        "name": "tomato",
        "emoji": "🍅",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["tomato"],
    },
    {
        "name": "onion",
        "emoji": "🧅",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["onion"],
    },
    {
        "name": "ginger",
        "emoji": "🫚",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["ginger"],
    },
    {
        "name": "potato",
        "emoji": "🥔",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["potato"],
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["vegetable"],
        "all_ingredients": ["mushroom"],
    },
    {
        "name": "pepper",
        "emoji": "🌶️",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["aromatic"],
        "all_ingredients": ["pepper"],
    },
    {
        "name": "coconut",
        "emoji": "🥥",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["coconut"],
    },
    {
        "name": "pineapple",
        "emoji": "🍍",
        "value": 0,
        "tool": False,
        "salt_level": 0,
        "cook_level": 0,
        "water_level": 0,
        "chop_level": 0,
        "edible": True,
        "ingredient_types": ["fruit"],
        "all_ingredients": ["pineapple"],
    },
]

cooking_tools = [
    {"name": "water", "emoji": "💧", "value": 0, "tool": True},
    {"name": "knife", "emoji": "🔪", "value": 0, "tool": True},
    {"name": "stove", "emoji": "🔥", "value": 0, "tool": True},
    {"name": "salt", "emoji": "🧂", "value": 0, "tool": True},
]

decorations_tools = [
    {"name": "scissors", "emoji": "✂️", "value": 0, "tool": True},
    {"name": "paint", "emoji": "🎨", "value": 0, "tool": True},
    {"name": "saw", "emoji": "🪚", "value": 0, "tool": True},
    {"name": "pen", "emoji": "🖊️", "value": 0, "tool": True},
]

decorations_ingredients = [
    {
        "name": "leaf",
        "emoji": "🍃",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["leaf"],
        "basic_item_count": 1,
    },
    {
        "name": "rock",
        "emoji": "🪨",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["rock"],
        "basic_item_count": 1,
    },
    {
        "name": "wood",
        "emoji": "🪵",
        "value": 0,
        "tool": False,
        "material_type": "wood",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["wood"],
        "basic_item_count": 1,
    },
    {
        "name": "paper",
        "emoji": "📄",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["paper"],
        "basic_item_count": 1,
    },
    {
        "name": "yarn",
        "emoji": "🧶",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["yarn"],
        "basic_item_count": 1,
    },
    {
        "name": "flower",
        "emoji": "🌸",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["flower"],
        "basic_item_count": 1,
    },
    {
        "name": "sunflower",
        "emoji": "🌻",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["sunflower"],
        "basic_item_count": 1,
    },
    {
        "name": "thread",
        "emoji": "🧵",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["thread"],
        "basic_item_count": 1,
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["mushroom"],
        "basic_item_count": 1,
    },
    {
        "name": "feather",
        "emoji": "🪶",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["feather"],
        "basic_item_count": 1,
    },
    {
        "name": "shell",
        "emoji": "🐚",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["shell"],
        "basic_item_count": 1,
    },
    {
        "name": "pinecone",
        "emoji": "🌲",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["pinecone"],
        "basic_item_count": 1,
    },
    {
        "name": "acorn",
        "emoji": "🌰",
        "value": 0,
        "tool": False,
        "material_type": "natural",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["acorn"],
        "basic_item_count": 1,
    },
    {
        "name": "bark",
        "emoji": "🪵",
        "value": 0,
        "tool": False,
        "material_type": "wood",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["bark"],
        "basic_item_count": 1,
    },
    {
        "name": "beads",
        "emoji": "📿",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["beads"],
        "basic_item_count": 1,
    },
    {
        "name": "ribbon",
        "emoji": "🎀",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["ribbon"],
        "basic_item_count": 1,
    },
    {
        "name": "cardboard",
        "emoji": "📦",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["cardboard"],
        "basic_item_count": 1,
    },
    {
        "name": "newspaper",
        "emoji": "📰",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["newspaper"],
        "basic_item_count": 1,
    },
    {
        "name": "buttons",
        "emoji": "🔘",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "hard",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["buttons"],
        "basic_item_count": 1,
    },
    {
        "name": "glitter",
        "emoji": "✨",
        "value": 0,
        "tool": False,
        "material_type": "artificial",
        "hardness": "soft",
        "paint_level": 0,
        "cut_level": 0,
        "decorated_level": 0,
        "basic_items": ["glitter"],
        "basic_item_count": 1,
    },
]

genetics_tools = [
    {"name": "growth serum", "emoji": "🌡️", "value": 0, "tool": True},
    {"name": "mutation catalyst", "emoji": "🧬", "value": 0, "tool": True},
    {"name": "respiratory reconfigurer", "emoji": "🌀", "value": 0, "tool": True},
    {"name": "metabolic accelerator", "emoji": "⚡", "value": 0, "tool": True},
]


genetics_ingredients = [
    {
        "name": "fish",
        "emoji": "🐟",
        "value": 0,
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "fish",
        "habitat": "water",
        "basic_animals": ["fish"],
        "basic_animal_count": 1,
    },
    {
        "name": "shark",
        "emoji": "🦈",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "fish",
        "habitat": "water",
        "basic_animals": ["shark"],
        "basic_animal_count": 1,
    },
    {
        "name": "octopus",
        "emoji": "🐙",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "mollusk",
        "habitat": "water",
        "basic_animals": ["octopus"],
        "basic_animal_count": 1,
    },
    {
        "name": "squid",
        "emoji": "🦑",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "gills",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "mollusk",
        "habitat": "water",
        "basic_animals": ["squid"],
        "basic_animal_count": 1,
    },
    {
        "name": "snake",
        "emoji": "🐍",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "reptile",
        "habitat": "land",
        "basic_animals": ["snake"],
        "basic_animal_count": 1,
    },
    {
        "name": "frog",
        "emoji": "🐸",
        "value": 0,
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "amphibian",
        "habitat": "land",
        "basic_animals": ["frog"],
        "basic_animal_count": 1,
    },
    {
        "name": "bird",
        "emoji": "🐦‍⬛",
        "value": 0,
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "omnivore",
        "family": "bird",
        "habitat": "air",
        "basic_animals": ["bird"],
        "basic_animal_count": 1,
    },
    {
        "name": "lizard",
        "emoji": "🦎",
        "value": 0,
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "reptile",
        "habitat": "land",
        "basic_animals": ["lizard"],
        "basic_animal_count": 1,
    },
    {
        "name": "turtle",
        "emoji": "🐢",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "reptile",
        "habitat": "land",
        "basic_animals": ["turtle"],
        "basic_animal_count": 1,
    },
    {
        "name": "elephant",
        "emoji": "🐘",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["elephant"],
        "basic_animal_count": 1,
    },
    {
        "name": "whale",
        "emoji": "🐳",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "mammal",
        "habitat": "water",
        "basic_animals": ["whale"],
        "basic_animal_count": 1,
    },
    {
        "name": "penguin",
        "emoji": "🐧",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "bird",
        "habitat": "land",
        "basic_animals": ["penguin"],
        "basic_animal_count": 1,
    },
    {
        "name": "panda",
        "emoji": "🐼",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["panda"],
        "basic_animal_count": 1,
    },
    {
        "name": "koala",
        "emoji": "🐨",
        "value": 0,
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["koala"],
        "basic_animal_count": 1,
    },
    {
        "name": "kangaroo",
        "emoji": "🦘",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["kangaroo"],
        "basic_animal_count": 1,
    },
    {
        "name": "tiger",
        "emoji": "🐯",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["tiger"],
        "basic_animal_count": 1,
    },
    {
        "name": "lion",
        "emoji": "🦁",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["lion"],
        "basic_animal_count": 1,
    },
    {
        "name": "giraffe",
        "emoji": "🦒",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["giraffe"],
        "basic_animal_count": 1,
    },
    {
        "name": "zebra",
        "emoji": "🦓",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "herbivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["zebra"],
        "basic_animal_count": 1,
    },
    {
        "name": "monkey",
        "emoji": "🐒",
        "value": 0,
        "tool": False,
        "size": "small",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "omnivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["monkey"],
        "basic_animal_count": 1,
    },
    {
        "name": "bear",
        "emoji": "🐻",
        "value": 0,
        "tool": False,
        "size": "large",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "omnivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["bear"],
        "basic_animal_count": 1,
    },
    {
        "name": "wolf",
        "emoji": "🐺",
        "value": 0,
        "tool": False,
        "size": "medium",
        "mutation_level": 0,
        "respiratory_type": "lungs",
        "metabolic_level": 0,
        "diet_type": "carnivore",
        "family": "mammal",
        "habitat": "land",
        "basic_animals": ["wolf"],
        "basic_animal_count": 1,
    },
]


potions_tools = [
    {"name": "vial", "emoji": "🧪", "value": 0, "tool": True},
    {"name": "mortar", "emoji": "🏺", "value": 0, "tool": True},
    {"name": "wand", "emoji": "🪄", "value": 0, "tool": True},
    {"name": "filter", "emoji": "🧫", "value": 0, "tool": True},
]

potions_ingredients = [
    {
        "name": "frog leg",
        "emoji": "🐸",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "soft",
        "ingredient_type": "animal",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["frog leg"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "bat wing",
        "emoji": "🦇",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "soft",
        "ingredient_type": "animal",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["bat wing"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "dragon scale",
        "emoji": "🐉",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "hard",
        "ingredient_type": "animal",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["dragon scale"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "unicorn horn",
        "emoji": "🦄",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "hard",
        "ingredient_type": "animal",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["unicorn horn"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "mandrake root",
        "emoji": "🌱",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "soft",
        "ingredient_type": "plant",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["mandrake root"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "mushroom",
        "emoji": "🍄",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "soft",
        "ingredient_type": "plant",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["mushroom"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "dandelion",
        "emoji": "🌼",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "soft",
        "ingredient_type": "plant",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["dandelion"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "rose petal",
        "emoji": "🌹",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "soft",
        "ingredient_type": "plant",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["rose petal"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "sunstone",
        "emoji": "☀️",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "hard",
        "ingredient_type": "mineral",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["sunstone"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "obsidian",
        "emoji": "⚫",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "hard",
        "ingredient_type": "mineral",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["obsidian"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "amber",
        "emoji": "🟠",
        "value": 0,
        "tool": False,
        "state_of_matter": "solid",
        "hardness": "hard",
        "ingredient_type": "mineral",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["amber"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "whispering wind",
        "emoji": "🌬️",
        "value": 0,
        "tool": False,
        "state_of_matter": "gas",
        "hardness": "soft",
        "ingredient_type": "essence",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["whispering wind"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "ghostly vapor",
        "emoji": "👻",
        "value": 0,
        "tool": False,
        "state_of_matter": "gas",
        "hardness": "soft",
        "ingredient_type": "essence",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["ghostly vapor"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "volcanic fumes",
        "emoji": "🌋",
        "value": 0,
        "tool": False,
        "state_of_matter": "gas",
        "hardness": "soft",
        "ingredient_type": "essence",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["volcanic fumes"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "dragon's breath",
        "emoji": "🔥",
        "value": 0,
        "tool": False,
        "state_of_matter": "gas",
        "hardness": "soft",
        "ingredient_type": "essence",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["dragon's breath"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "basilisk venom",
        "emoji": "⚗️",
        "value": 0,
        "tool": False,
        "state_of_matter": "liquid",
        "hardness": "soft",
        "ingredient_type": "animal",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["basilisk venom"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "morning dew",
        "emoji": "💧",
        "value": 0,
        "tool": False,
        "state_of_matter": "liquid",
        "hardness": "soft",
        "ingredient_type": "essence",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["morning dew"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "kraken ink",
        "emoji": "🦑",
        "value": 0,
        "tool": False,
        "state_of_matter": "liquid",
        "hardness": "soft",
        "ingredient_type": "animal",
        "magical_level": "magical",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["kraken ink"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "honey nectar",
        "emoji": "🍯",
        "value": 0,
        "tool": False,
        "state_of_matter": "liquid",
        "hardness": "soft",
        "ingredient_type": "plant",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["honey nectar"],
        "basic_ingredient_count": 1,
    },
    {
        "name": "tree sap",
        "emoji": "🌳",
        "value": 0,
        "tool": False,
        "state_of_matter": "liquid",
        "hardness": "soft",
        "ingredient_type": "plant",
        "magical_level": "mundane",
        "enchantment_level": 0,
        "filtered": False,
        "extraction_level": 0,
        "basic_ingredients": ["tree sap"],
        "basic_ingredient_count": 1,
    },
]


TOOLS = {
    "cooking": cooking_tools,
    "decorations": decorations_tools,
    "genetics": genetics_tools,
    "potions": potions_tools,
}

INGREDIENTS = {
    "cooking": cooking_ingredients,
    "decorations": decorations_ingredients,
    "genetics": genetics_ingredients,
    "potions": potions_ingredients,
}


cooking_system_prompt = """
You are controlling the semantics of a cooking game. You will see two items and the features of the item you get from combining them. Your job is to generate an appropriate name and string of up to three emoji that describe the item. Please respond in JSON format.

The names should be informative and make it possible for the player to know the relevant features so they can learn the rules.
"""

decorations_system_prompt = """
You are controlling the dynamics of a decorations game. Given two items, your job is to generate the item you get from combining them, along with its value.

BASIC RULES:
1. Each item has a value (-100 to 100) representing how cool of an object it is.
2. Basic items that aren't crafted have a value of 0.
3. Tools (scissors, paint, saw, pen) are used to modify ingredients. They always have a value of 0.
4. Combining two tools creates a new, potentially very useful tool. But combining non-basic tools doesn't make anything.
5. Ingredients can be combined to make new decorations.

TOOL USE RULES:
1. Pen: Using the pen on artificial things (cardboard, paper, newspaper) makes them more valuable. It should get a descriptor like "drawn" or "decorated." Using the pen on natural things (wood, leaves, flowers) makes them less valuable. It should get a descriptor like "ruined" or "defaced."
2. Saw: Using the saw on wood and wood-derived items makes them more valuable. It should get a descriptor like "cut" or "shaped." Using the saw on non-wood items makes them less valuable. It should get a descriptor like "damaged" or "broken."
3. Scissors: Using scissors on soft items (paper, ribbon, yarn) makes them more valuable. It should get a descriptor like "cut" or "shaped." Using scissors on hard items (wood, rock) makes them less valuable. It should get a descriptor like "damaged" or "broken."
4. Paint: Adding paint to an item makes it painted. It should get a descriptor like "painted." Adding paint a second time makes it messy and reduces value. It should get a descriptor like "messy" or "over-painted."

COMBINATION RULES:
1. Natural + Artificial: Combining artificial items (cardboard, paper) with natural items (leaves, flowers) creates more valuable decorations than combining two natural items or two artificial items.
2. Soft + Hard: Combining soft items (paper, ribbon) with hard items (wood, rock) creates more interesting decorations than combining two soft items or two hard items.
3. Overcomplication: A decoration that combines more than three different basic items should be less valuable than a decoration that combines fewer than 3 basic items.

VALUE RULES:
1. Artificial items decorated with pen should be more valuable than undecorated items (value +20-30). Natural items decorated with pen should be less valuable (value -20-30).
2. Wood items cut with saw should be more valuable than uncut items (value +15-25). Non-wood items cut with saw should be less valuable (value -15-25).
3. Soft items cut with scissors should be more valuable than uncut items (value +15-25). Hard items cut with scissors should be less valuable (value -15-25).
4. Painted items should be more valuable than unpainted items (value +10-20), but over-painting should make items worse (value -20-30).
5. Natural + artificial combinations should be more valuable than other combinations (value +20-30).
6. Decorations with more than 3 basic items should be less valuable than decorations with fewer than 3 basic items (value -10-20 per extra item).

Think step by step about what the resulting item should be, what its value should be, and what emoji to use. We want a player who is trying to make the most valuable decoration to be able to learn the rules. In generating the names for the resulting decorations, you should use descriptive adjectives and names that help people learn the rules.

You should always respond with your reasoning between the <reasoning> and </reasoning> tags, and valid JSON between the <output> and </output> tags.
"""

genetics_system_prompt = """
You are controlling the dynamics of a gene splicing game. Given two animals, or animals and tools, your job is to generate the hybrid or modified animal you get from combining them, along with its value.

BASIC RULES:
1. Each animal has a value (-100 to 100) representing how cool of an animal it is.
2. Basic animals that aren't the product of gene splicing have a value of 2.
3. Tools (growth serum, mutation catalyst, respiratory reconfigurer, metabolic accelerator) are used to modify animals. They always have a value of 0.
4. Combining two tools creates a new, potentially very useful tool. But combining non-basic tools doesn't make anything.
5. Animals can be combined to make new hybrids.

TOOL USE RULES:
1. Growth Serum: Using growth serum on small animals makes them better. It should get a descriptor like "mega" or "giant." Using it on large animals makes them worse. It should get a descriptor like "overgrown" or "deformed."
2. Mutation Catalyst: First mutation makes animals worse. It should get a descriptor like "mutant." Second mutation makes them better. It should get a descriptor like "super" or "enhanced." Third mutation makes them much worse. It should get a descriptor like "corrupted" or "twisted."
3. Respiratory Reconfigurer: Reconfiguring gills to lungs (or vice versa) makes animals worse. It should get a descriptor like "with lungs" or "with gills." Combining reconfigured land/marine animals makes better hybrids. It should get a descriptor like "amphibious" or "dual-breathing."
4. Metabolic Accelerator: Using it on carnivores/omnivores makes them better. It should get a descriptor like "enhanced" or "boosted." Using it on herbivores makes them worse. It should get a descriptor like "malnourished" or "weakened."

COMBINATION RULES:
1. Family Crossing: Combining animals from different families (reptile + mammal) makes better hybrids than combining within the same family.
2. Size Compatibility: Combining animals of similar size makes better hybrids than combining animals of very different sizes.
3. Habitat Compatibility: Combining animals from similar habitats (land + land, water + water) makes better hybrids than combining animals from different habitats.
4. Overcomplication: Hybrids with more than three basic animals get worse.

VALUE RULES:
1. Growth serum on small animals should make them better (value +20-30). Growth serum on large animals should make them worse (value -20-30). Growth serum on medium animals can go either way (value -10 to +10).
2. First mutation should make animals worse (value -20-30). Second mutation should make them better (value +30-40). Third mutation should make them much worse (value -40-50).
3. Respiratory reconfiguration should make animals worse (value -10-20). Combining reconfigured land/marine animals should make better hybrids (value +30-40).
4. Metabolic accelerator on carnivores/omnivores should make them better (value +20-30). Metabolic accelerator on herbivores should make them worse (value -20-30).
5. Cross-family hybrids should be more valuable than same-family hybrids (value +20-30).
6. Hybrids with more than 3 basic animals should be less valuable (value -30-40).

Think step by step about what the resulting animal should be, what its value should be, and what emoji to use. We want a player who is trying to make the most valuable animal to be able to learn the rules. In generating the names for the resulting animals, you should use descriptive adjectives and names that help people learn the rules.

You should always respond with your reasoning between the <reasoning> and </reasoning> tags, and valid JSON between the <output> and </output> tags.
"""

potions_system_prompt = """
You are controlling the dynamics of a potion brewing game. Given two items, your job is to generate the potion you get from combining them, along with its potency.

BASIC RULES:
1. Each potion has a potency (-100 to 100) representing how effective it is.
2. Basic ingredients that aren't brewed have a potency of 0.
3. Tools (vial, mortar, wand, filter) are used to modify ingredients. They always have a potency of 0.
4. Combining two tools creates a new, potentially very useful tool. But combining non-basic tools doesn't make anything.
5. Ingredients can be combined to make new potions.

TOOL USE RULES:
1. Vial: Using the vial on plant ingredients makes them better. It should get a descriptor like "extract" or "essence." Using it on non-plant ingredients (or combinations with at least one non-plant ingredient) makes them worse. It should get a descriptor like "spoiled" or "rotten."
2. Mortar: Using the mortar on hard ingredients (e.g. minerals, scales) makes them better. It should get a descriptor like "ground" or "powdered." Using it on soft ingredients (e.g. flowers, leaves), or combinations with at least one non-hard ingredient, makes them worse. It should get a descriptor like "pulverized" or "crushed."
3. Wand: Using a wand on anything should make it better and give it a descriptor like "flickering" or "unstable." Using a wand a second time should make it much better and give it a descriptor like "glowing" or "enchanted." Subsequnt uses of the wand should make the item worse. It should get a descriptor like "corrupted" or "twisted."
4. Filter: Using the filter on liquid ingredients makes them better. It should get a descriptor like "purified" or "filtered." Using it on solid or gaseous ingredients makes them worse. If it is a solid, it should get a descriptor like "drained" or "dry." If it is gaseous, it should get a descriptor like "filtered" or "purified."

COMBINATION RULES:
1. States of Matter: Combining ingredients of different states (liquid + solid, solid + powder) makes better potions than combining ingredients in the same state. Combining items with the same sate of matter should make the result a bit worse.
2. Magical-Mundane: Combining ingredients that are magical, meaning they don't exist in the real world (like unicorn horn and dragon scale) with mundane ingredients (common herbs, stones) makes better potions than combining two magical or two mundane ingredients. Combining two mundane ingredients should make the result a bit worse.
3. Overcomplication: Potions with more than three basic ingredients get worse.

VALUE RULES:
1. Vial on plant ingredients should make them better (value +20-30). Vial on animal ingredients should make them worse (value -20-30).
2. Mortar on hard ingredients should make them better (value +15-25). Mortar on soft ingredients should make them worse (value -15-25).
3. First wand enchantment should make ingredients worse (value -10-20). Second enchantment should make them better (value +20-30). Third enchantment should make them much worse (value -30-40).
4. Filter on liquid ingredients should make them better (value +15-25). Filter on solid ingredients should make them worse (value -15-25).
5. Different states of matter combinations should make things more valuable (value +15-25) and same-state combinations should make things a bit worse (value -5-15).
6. Magical-mundane combinations should make things more valuable (value +25-35) and same-magicalness combinations should make things a bit worse (value -5-15).
7. Potions with more than 3 basic ingredients should be lower value (value -20-30 per extra ingredient).

Think step by step about what the resulting potion should be, what its potency should be, and what emoji to use. We want a player who is trying to make the most potent potion to be able to learn the rules. In generating the names for the resulting potions, you should use descriptive adjectives and names that help people learn the rules.

You should always respond with your reasoning between the <reasoning> and </reasoning> tags, and valid JSON between the <output> and </output> tags.
"""

SYSTEM_PROMPTS = {
    "cooking": cooking_system_prompt,
    "decorations": decorations_system_prompt,
    "genetics": genetics_system_prompt,
    "potions": potions_system_prompt,
}


cooking_ic_examples = [
    {
        "input": [
            {"name": "raw meat", "emoji": "🥩", "value": 0, "durable": False},
            {"name": "knife", "emoji": "🔪", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for knife, using a knife on raw meat should make it sliced. Since raw meat is inedible (value 0), sliced raw meat should also be inedible. The knife is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "sliced raw meat",
            "value": 0,
            "durable": False,
            "emoji": "🔪🥩",
        },
    },
    {
        "input": [
            {"name": "sliced raw meat", "emoji": "🔪🥩", "value": 0, "durable": False},
            {"name": "stove", "emoji": "🔥", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for stove and the value rules, cooking sliced meat should make it edible. The value rules specify that sliced and cooked ingredients should be more valuable (value +10-20). I'll set it to 15 to show the improvement.",
        "output": {
            "name": "cooked sliced meat",
            "value": 15,
            "durable": False,
            "emoji": "🔪🍖",
        },
    },
    {
        "input": [
            {"name": "raw rice", "emoji": "🌾", "value": 0, "durable": False},
            {"name": "water", "emoji": "💧", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for water, adding water to rice makes it soaked. The value rules specify that soaking grains doesn't change value by itself, but prepares them for better cooking later.",
        "output": {
            "name": "soaked rice",
            "value": 0,
            "durable": False,
            "emoji": "💧🌾",
        },
    },
    {
        "input": [
            {"name": "soaked rice", "emoji": "💧🌾", "value": 0, "durable": False},
            {"name": "stove", "emoji": "🔥", "value": 0, "durable": True},
        ],
        "reasoning": "Following the value rules, cooking soaked grains should dramatically increase value (+20-30). I'll set it to 25 to show the significant improvement from soaking and cooking.",
        "output": {
            "name": "cooked rice",
            "value": 25,
            "durable": False,
            "emoji": "🍚",
        },
    },
    {
        "input": [
            {"name": "cooked rice", "emoji": "🍚", "value": 25, "durable": False},
            {"name": "salt", "emoji": "🧂", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for salt, adding salt to a dish should improve its value (+10-20). The cooked rice has a value of 25, so adding salt should increase it to 35. This is the first use of salt, so it should be a positive change.",
        "output": {
            "name": "salted rice",
            "value": 35,
            "durable": False,
            "emoji": "🧂🍚",
        },
    },
]

decorations_ic_examples = [
    {
        "input": [
            {"name": "pen", "emoji": "🖊️", "value": 0, "durable": True},
            {"name": "paper", "emoji": "📄", "value": 0, "durable": False},
        ],
        "reasoning": "Following the tool use rules for pen and the value rules, using a pen on an artificial item like paper should make it more valuable. The value rules specify a value increase of +20-30. I'll set it to 25 to show the significant improvement. The pen is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "drawn paper",
            "value": 25,
            "durable": False,
            "emoji": "🖊️📄",
        },
    },
    {
        "input": [
            {"name": "pen", "emoji": "🖊️", "value": 0, "durable": True},
            {"name": "leaf", "emoji": "🍃", "value": 0, "durable": False},
        ],
        "reasoning": "Following the tool use rules for pen and the value rules, using a pen on a natural item like a leaf should make it less valuable. The value rules specify a value decrease of -20-30. I'll set it to -25 to show the significant negative effect. The pen is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "defaced leaf",
            "value": -25,
            "durable": False,
            "emoji": "🖊️🍃",
        },
    },
    {
        "input": [
            {"name": "saw", "emoji": "🪚", "value": 0, "durable": True},
            {"name": "wood", "emoji": "🪵", "value": 0, "durable": False},
        ],
        "reasoning": "Following the tool use rules for saw and the value rules, using a saw on wood should make it more valuable. The value rules specify a value increase of +15-25. I'll set it to 20 to show the improvement. The saw is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "cut wood",
            "value": 20,
            "durable": False,
            "emoji": "🪚🪵",
        },
    },
    {
        "input": [
            {"name": "cardboard", "emoji": "📦", "value": 0, "durable": False},
            {"name": "leaf", "emoji": "🍃", "value": 0, "durable": False},
        ],
        "reasoning": "Following the combination rules for Natural + Artificial and the value rules, combining an artificial item (cardboard) with a natural item (leaf) should create a more valuable decoration. The value rules specify a value increase of +20-30. I'll set it to 25 to show the significant improvement.",
        "output": {
            "name": "leaf-covered box",
            "value": 25,
            "durable": False,
            "emoji": "📦🍃",
        },
    },
    {
        "input": [
            {"name": "paint", "emoji": "🎨", "value": 0, "durable": True},
            {"name": "painted acorn", "emoji": "🎨🌰", "value": 15, "durable": False},
        ],
        "reasoning": "Following the tool use rules for paint and the value rules, adding paint a second time should make the item messy and reduce its value. The value rules specify a value decrease of -20-30. Since the current value is 15, I'll set it to -10 to show the significant negative effect. The paint is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "messy over-painted acorn",
            "value": -10,
            "durable": False,
            "emoji": "🎨🌰",
        },
    },
]

genetics_ic_examples = [
    {
        "input": [
            {"name": "frog", "emoji": "🐸", "value": 2, "durable": False},
            {"name": "growth serum", "emoji": "🌡️", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for growth serum and the value rules, using growth serum on a small animal like a frog should make it better. The value rules specify a value increase of +20-30. I'll set it to 25 to show the significant improvement. The growth serum is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "mega-frog",
            "value": 25,
            "durable": False,
            "emoji": "🌡️🐸",
        },
    },
    {
        "input": [
            {"name": "elephant", "emoji": "🐘", "value": 2, "durable": False},
            {"name": "growth serum", "emoji": "🌡️", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for growth serum and the value rules, using growth serum on a large animal like an elephant should make it worse. The value rules specify a value decrease of -20-30. I'll set it to -25 to show the significant negative effect. The growth serum is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "overgrown elephant",
            "value": -25,
            "durable": False,
            "emoji": "🌡️🐘",
        },
    },
    {
        "input": [
            {"name": "tiger", "emoji": "🐯", "value": 2, "durable": False},
            {"name": "mutation catalyst", "emoji": "🧬", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for mutation catalyst and the value rules, the first mutation should make the animal worse. The value rules specify a value decrease of -20-30. I'll set it to -25 to show the significant negative effect. The mutation catalyst is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "mutant tiger",
            "value": -25,
            "durable": False,
            "emoji": "🧬🐯",
        },
    },
    {
        "input": [
            {"name": "mutant tiger", "emoji": "🧬🐯", "value": -25, "durable": False},
            {"name": "mutation catalyst", "emoji": "🧬", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for mutation catalyst and the value rules, the second mutation should make the animal better than the original. The value rules specify a value increase of +30-40 from the first mutation. Since the current value is -25, I'll set it to 35 to show the significant improvement. The mutation catalyst is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "super-mutant tiger",
            "value": 35,
            "durable": False,
            "emoji": "🧬🐯",
        },
    },
    {
        "input": [
            {"name": "lizard", "emoji": "🦎", "value": 2, "durable": False},
            {"name": "koala", "emoji": "🐨", "value": 2, "durable": False},
        ],
        "reasoning": "Following the combination rules for Family Crossing and the value rules, combining animals from different families (reptile + mammal) should make a better hybrid. The value rules specify a value increase of +20-30. I'll set it to 25 to show the significant improvement.",
        "output": {
            "name": "lizoala",
            "value": 25,
            "durable": False,
            "emoji": "🦎🐨",
        },
    },
]


potions_ic_examples = [
    {
        "input": [
            {
                "name": "rose petal",
                "emoji": "🌹",
                "value": 0,
                "durable": False,
            },
            {"name": "vial", "emoji": "🧪", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for vial and the value rules, using a vial on a plant ingredient like rose petal should make it better. The value rules specify a value increase of +20-30. I'll set it to 25 to show the significant improvement. The vial is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "rose extract",
            "value": 25,
            "durable": False,
            "emoji": "🧪🌹",
        },
    },
    {
        "input": [
            {
                "name": "frog leg",
                "emoji": "🐸",
                "value": 0,
                "durable": False,
            },
            {"name": "vial", "emoji": "🧪", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for vial and the value rules, using a vial on an animal ingredient like frog leg should make it worse. The value rules specify a value decrease of -20-30. I'll set it to -25 to show the significant negative effect. The vial is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "spoiled frog leg",
            "value": -25,
            "durable": False,
            "emoji": "🧪🐸",
        },
    },
    {
        "input": [
            {
                "name": "crystal",
                "emoji": "💎",
                "value": 0,
                "durable": False,
            },
            {"name": "mortar", "emoji": "🏺", "value": 0, "durable": True},
        ],
        "reasoning": "Following the tool use rules for mortar and the value rules, using a mortar on a hard ingredient like crystal should make it better. The value rules specify a value increase of +15-25. I'll set it to 20 to show the improvement. The mortar is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "ground crystal",
            "value": 20,
            "durable": False,
            "emoji": "🏺💎",
        },
    },
    {
        "input": [
            {"name": "wand", "emoji": "🪄", "value": 0, "durable": True},
            {
                "name": "fairy dust",
                "emoji": "✨",
                "value": 0,
                "durable": False,
            },
        ],
        "reasoning": "Following the tool use rules for wand and the value rules, the first enchantment should make the ingredient worse. The value rules specify a value decrease of -10-20. I'll set it to -15 to show the negative effect. The wand is a tool, so it should be preserved in the emoji.",
        "output": {
            "name": "flickering fairy dust",
            "value": -15,
            "durable": False,
            "emoji": "🪄✨",
        },
    },
    {
        "input": [
            {
                "name": "sea water",
                "emoji": "🌊",
                "value": 0,
                "durable": False,
            },
            {
                "name": "phoenix feather",
                "emoji": "🔥",
                "value": 0,
                "durable": False,
            },
        ],
        "reasoning": "Following the combination rules for Magical-Mundane and the value rules, combining a magical ingredient (phoenix feather) with a mundane ingredient (sea water) should make it more valuable. The value rules specify a combination adds +25-35. I'll set it to 30 to show the significant improvement.",
        "output": {
            "name": "steaming phoenix potion",
            "value": 30,
            "durable": False,
            "emoji": "🌊🔥",
        },
    },
]

IC_EXAMPLES = {
    "cooking": cooking_ic_examples,
    "decorations": decorations_ic_examples,
    "genetics": genetics_ic_examples,
    "potions": potions_ic_examples,
}
